[package]
name = "sims"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3.0"
rand = "0.8.5"
rayon = "1.8.0"
gif = "0.12.0"
image = "0.24.7"
tqdm = "0.6.0"
